name: Build and deploy PegasusHub Jekyll site to GitHub Pages

on: push

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Sub Path
        id: get-sub-path
        shell: bash
        run: |
          REF="${{ github.ref}}"
          NAME=$(basename $REF)
          TYPE=$(basename $(dirname $REF))
          if [ $TYPE == 'heads' ]; then
              NAME=${NAME}dev
          elif [ $TYPE == 'tags' ]; then
              NAME=$NAME
          else
              NAME=''
          fi
          echo "SUB_PATH=$NAME" >> $GITHUB_OUTPUT
        
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_history: true
          target_branch: 'gh-pages'
          target_path: docs/${{ steps.get-sub-path.outputs.SUB_PATH }}
